const constants = {
    NEW_SERVER_ROOT: "NEW_SERVER_ROOT",
    USER_AUTHENTICATION: "USER_AUTHENTICATION",
    ADD_ENTRY: "ADD_ENTRY",
    DELETE_ENTRY: "DELETE_ENTRY",
    UPDATE_ENTRY: "UPDATE_ENTRY"
};
export default constants;
