const constants = {
    NEW_SERVER_ROOT: "NEW_SERVER_ROOT",
    AUTHENTICATED: "AUTHENTICATED",
    UNAUTHENTICATED: "UNAUTHENTICATED",
    AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
    NEW_USER_FAILED: "NEW_USER_FAILED",

    //Entries
    UPDATE_ENTRIES: "UPDATE_ENTRIES",
    CREATE_ENTRY: "ADD_ENTRY",
    DELETE_ENTRY: "DELETE_ENTRY",
    UPDATE_ENTRY: "UPDATE_ENTRY",
    START_EDIT_ENTRY: "START_EDIT_ENTRY",
    STOP_EDIT_ENTRY: "STOP_EDIT_ENTRY",

    //Entry types
    DESCRIPTION: "DESCRIPTION",
    TASK: "TASK",
    NOTIFICATION: "NOTIFICATION",
    DOCUMENT: "DOCUMENT"
};
export default constants;
